name: Java CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    name: Build && Test
    runs-on: ubuntu-18.04
    env:
      POM_FILE: pom.xml
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1 
        with:
          java-version: 11
      - name: Build 
        run: mvn -B package -DskipTests --file $POM_FILE
      - name: Run tests
        run: mvn test --file $POM_FILE
      - name: Say something nice
        if: success()
        run: echo \
           _   _   _____   _____   ______ \n \
          | \ | | |_   _| / ____| |  ____| \n \
          |  \| |   | |  | |      | |__   \n \
          | . ` |   | |  | |      |  __|  \n \
          | |\  |_ _| |_ | |____ _| |____ \n \
          |_| \_(_)_____(_)_____(_)______| \n 
          
